### ISSUE TITLE
Error with running "read dicom image" following your guide in Github. 

### ISSUE THREAD

**Issue by paulxiong** [MaciejMazurowski/duke-dbt-data#1]
![image](https://user-images.githubusercontent.com/75286/103122105-d2de6a00-4633-11eb-86fd-32905be23f9d.png)

**Comment by mateuszbuda** [comment]
Hi @paulxiong, thank you for testing the code.
Please note that this is just a warning.
It appears because of a mismatch between pixel array data type, which is int16, and Bits Stored DICOM header.
Even though the Bits Stored value is 10, the pixel array values are correctly represented with int16.
The Bits Stored value is for some reason not matching the pixel array data type, but it was set like that in the original DICOM files and we did not change it.

**Comment by paulxiong** [comment]
@mateuszbuda  yes, you are correct. Ignore this warning (only showed in docker) the image can be read and displayed w/o issues. Thanks.
